todo/urls.py
from django.urls import path
from .views import (
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    ToggleTaskStatusView
)


urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),

    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path('tasks/<int:pk>/toggle-status/', ToggleTaskStatusView.as_view(), name='task-toggle-status'),

    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]

app_name = "todo"

todo_list_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("todo.urls", namespace="urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=255)
    datetime = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    status = models.BooleanField(default=False)
    tag = models.ManyToManyField(Tag, related_name="tasks", blank=True)

    def __str__(self):
        return self.content

todo/forms.py
from django import forms
from todo.models import Task, Tag


class TaskForm(forms.ModelForm):
    tag = forms.ModelMultipleChoiceField(
        required=False,
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    deadline = forms.DateField(
        required=False,
        widget=forms.DateInput(attrs={'type': 'date'})
    )

    class Meta:
        model = Task
        fields = ["content", "deadline", "tag"]

todo/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import generic, View
from django.views.decorators.csrf import csrf_exempt

from todo.forms import TaskForm
from todo.models import Tag, Task


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo:tag-list")


class TaskListView(generic.ListView):
    model = Task


class TaskCreateView(generic.CreateView):
    model = Task
    success_url = reverse_lazy("todo:task-list")
    form_class = TaskForm


class TaskUpdateView(generic.UpdateView):
    model = Task
    success_url = reverse_lazy("todo:task-list")
    form_class = TaskForm


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo:task-list")


class ToggleTaskStatusView(View):
    def post(self, request, *args, **kwargs):
        task = get_object_or_404(Task, pk=self.kwargs['pk'])
        task.status = not task.status
        task.save()
        return redirect(reverse_lazy("todo:task-list"))

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Todo List</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
        crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">

      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}

    </div>
    <div class="col-sm-10 ">

      {% block content %}{% endblock %}

    </div>
  </div>
</div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group m-2">
  <li class="list-group-item"><a href="{% url 'todo:task-list' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo:tag-list' %}">All tags</a></li>
</ul>

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Tag '{{ tag.name }}'?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}


{% block content %}
  <h1>
    Tags
    <a href="{% url 'todo:tag-create' %}" class="btn btn-primary link-to-page">Add</a>
  </h1>



  {% if tag_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for tag in tag_list %}
        <tr>
          <td>
            {{ tag.id }}
          </td>
          <td>
            {{ tag.name }}
          </td>
          <td>
            <a href="{% url 'todo:tag-update' pk=tag.id %}">
              Update
            </a>
          </td>
          <td>
            <a style="color: red"
               href="{% url 'todo:tag-delete' pk=tag.id %}">
              Delete
            </a>
          </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
    <p>There are no tags in the service.</p>
  {% endif %}
{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Task '{{ task.content }}'?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo/task_list.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="mb-4">
    TODO list
    <a href="{% url 'todo:task-create' %}" class="btn btn-primary link-to-page">
      Add Task
    </a>
  </h1>

  {% if task_list %}
    {% for task in task_list %}
      <h5>
        {{ task.content }}
        {% if task.status %}
          <span class="text-success">[Done]</span>
          <form action="{% url 'todo:task-toggle-status' pk=task.id %}" method="post" style="display:inline;">
            {% csrf_token %}
            <button type="submit" class="btn btn-secondary link-to-page">
              Undo
            </button>
          </form>
        {% else %}
          <span class="text-danger">[Not Done]</span>
          <form action="{% url 'todo:task-toggle-status' pk=task.id %}" method="post" style="display:inline;">
            {% csrf_token %}
            <button type="submit" class="btn btn-success link-to-page">
              Complete
            </button>
          </form>
        {% endif %}
      </h5>
      <p class="mb-2">
        Created: {{ task.datetime|date:"F j, Y, g:i a" }} |
        <span class="text-danger">Deadline: {{ task.deadline|date:"F j, Y, g:i a" }}</span>
      </p>
      {% if task.tag.all %}
        <p class="text-muted mb-2">Tags:
          {% for tag in task.tag.all %}
            #{{ tag }}
          {% endfor %}
        </p>
      {% endif %}
      <p>
        <a href="{% url 'todo:task-update' pk=task.id %}">Update</a>
        <a href="{% url 'todo:task-delete' pk=task.id %}">Delete</a>
      </p>
      <hr>
    {% endfor %}
  {% else %}
    <p>There are no tags in the service.</p>
  {% endif %}
{% endblock %}